//! Rendering the OIT run into a friction report (Markdown).
//!
//! Kept pure and string-only so the report format is unit-tested without any
//! live run. The live binary feeds it real [`UseCaseRun`] records.

use super::usecases::{Category, Friction};

/// The result of driving one use case through azork.
#[derive(Debug, Clone)]
pub struct UseCaseRun {
    pub id: String,
    pub title: String,
    pub category: Category,
    /// Commands sent and the (trimmed) responses observed.
    pub transcript: Vec<(String, String)>,
    /// Friction observed while running this use case.
    pub friction: Vec<Friction>,
}

impl UseCaseRun {
    /// A use case "passed" cleanly when it surfaced no friction.
    pub fn clean(&self) -> bool {
        self.friction.is_empty()
    }
}

/// Everything a live OIT run needs to produce its report.
#[derive(Debug, Clone, Default)]
pub struct ReportData {
    pub subscription: String,
    pub tenant_name: String,
    pub region: String,
    /// Resource groups created (and later torn down) during the run.
    pub resource_groups: Vec<String>,
    /// Per-use-case run records.
    pub runs: Vec<UseCaseRun>,
    /// Improvements made to azork in response to friction (free text bullets).
    pub improvements: Vec<String>,
    /// Narrative of live-tenant findings surfaced and fixed during the loop.
    pub live_findings: Vec<String>,
    /// GitHub issue references opened for friction (e.g. "#12").
    pub issues: Vec<String>,
    /// Teardown outcome lines (deletion + verification).
    pub teardown: Vec<String>,
}

impl ReportData {
    /// Total friction observations across all runs.
    pub fn total_friction(&self) -> usize {
        self.runs.iter().map(|r| r.friction.len()).sum()
    }

    /// Render the full Markdown friction report.
    pub fn to_markdown(&self) -> String {
        let mut s = String::new();
        s.push_str("# AzZork Outside-In-Testing (OIT) Friction Report\n\n");
        s.push_str(
            "Generated by the `azork-oit` agent, which uses AzZork like a real user \
             against a live Azure tenant, records friction, and feeds fixes back into \
             AzZork.\n\n",
        );

        s.push_str("## Run context\n\n");
        s.push_str(&format!("- **Tenant:** {}\n", nz(&self.tenant_name)));
        s.push_str(&format!("- **Subscription:** {}\n", nz(&self.subscription)));
        s.push_str(&format!("- **Region:** {}\n", nz(&self.region)));
        s.push_str(&format!("- **Use cases exercised:** {}\n", self.runs.len()));
        s.push_str(&format!(
            "- **Friction observations:** {}\n",
            self.total_friction()
        ));
        if !self.resource_groups.is_empty() {
            s.push_str(&format!(
                "- **Resource groups created:** {}\n",
                self.resource_groups.join(", ")
            ));
        }
        s.push('\n');

        s.push_str("## Guardrails enforced\n\n");
        s.push_str("- **Cost:** no action estimated over $500; only free/cheap SKUs (resource groups, Standard_LRS storage).\n");
        s.push_str("- **Cleanup:** every created resource is tagged `azork-oit=1 owner=azork-oit ttl=<epoch>` and torn down (verified).\n");
        s.push_str("- **Non-destructive:** only resources bearing the agent's own tags are ever mutated/deleted.\n");
        s.push_str(&format!(
            "- **Isolation:** all test resources in `azork-oit-*` resource groups in `{}`.\n\n",
            nz(&self.region)
        ));

        s.push_str("## Use cases\n\n");
        s.push_str("| # | Use case | Category | Result |\n");
        s.push_str("|---|----------|----------|--------|\n");
        for (i, run) in self.runs.iter().enumerate() {
            let result = if run.clean() {
                "clean".to_string()
            } else {
                format!("{} friction", run.friction.len())
            };
            s.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                i + 1,
                run.title,
                run.category.label(),
                result
            ));
        }
        s.push('\n');

        if self.total_friction() > 0 {
            s.push_str("## Friction found\n\n");
            for run in self.runs.iter().filter(|r| !r.clean()) {
                s.push_str(&format!("### {} — {}\n\n", run.id, run.title));
                for f in &run.friction {
                    s.push_str(&format!(
                        "- **[{}]** `{}` — {}\n",
                        f.kind.label(),
                        f.command,
                        f.note
                    ));
                }
                s.push('\n');
            }
        } else {
            s.push_str("## Friction found\n\nNo friction surfaced in this run.\n\n");
        }

        if !self.live_findings.is_empty() {
            s.push_str("## Live-tenant findings (surfaced and fixed)\n\n");
            for f in &self.live_findings {
                s.push_str(&format!("- {f}\n"));
            }
            s.push('\n');
        }

        if !self.improvements.is_empty() {
            s.push_str("## Improvements fed back into AzZork\n\n");
            for imp in &self.improvements {
                s.push_str(&format!("- {imp}\n"));
            }
            s.push('\n');
        }

        if !self.issues.is_empty() {
            s.push_str("## Issues opened\n\n");
            for iss in &self.issues {
                s.push_str(&format!("- {iss}\n"));
            }
            s.push('\n');
        }

        s.push_str("## Teardown\n\n");
        if self.teardown.is_empty() {
            s.push_str("_No live resources were created (offline/dry run)._\n");
        } else {
            for line in &self.teardown {
                s.push_str(&format!("- {line}\n"));
            }
        }
        s.push('\n');

        s
    }
}

/// Substitute a dash for empty strings so the report never has blank cells.
fn nz(s: &str) -> &str {
    if s.trim().is_empty() {
        "-"
    } else {
        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::oit::usecases::{Friction, FrictionKind};

    fn sample() -> ReportData {
        ReportData {
            subscription: "sub-123".to_string(),
            tenant_name: "DefenderATEVET17".to_string(),
            region: "eastus".to_string(),
            resource_groups: vec!["azork-oit-nav".to_string()],
            runs: vec![
                UseCaseRun {
                    id: "nav-look".to_string(),
                    title: "Look around".to_string(),
                    category: Category::Navigation,
                    transcript: vec![("look".to_string(), "You are in rg1.".to_string())],
                    friction: vec![],
                },
                UseCaseRun {
                    id: "disc-intent".to_string(),
                    title: "Resolve intent".to_string(),
                    category: Category::Discovery,
                    transcript: vec![("frobnicate".to_string(), "stirs nothing".to_string())],
                    friction: vec![Friction {
                        command: "frobnicate".to_string(),
                        kind: FrictionKind::Unresolved,
                        note: "not resolved".to_string(),
                    }],
                },
            ],
            improvements: vec!["Added a `create` guidance path".to_string()],
            live_findings: vec!["Bounded the live backend for large subscriptions".to_string()],
            issues: vec!["#42 — unresolved intent handling".to_string()],
            teardown: vec!["Deleted azork-oit-nav (verified absent)".to_string()],
        }
    }

    #[test]
    fn report_has_all_sections() {
        let md = sample().to_markdown();
        assert!(md.contains("# AzZork Outside-In-Testing (OIT) Friction Report"));
        assert!(md.contains("## Run context"));
        assert!(md.contains("## Guardrails enforced"));
        assert!(md.contains("## Use cases"));
        assert!(md.contains("## Friction found"));
        assert!(md.contains("## Improvements fed back into AzZork"));
        assert!(md.contains("## Issues opened"));
        assert!(md.contains("## Teardown"));
    }

    #[test]
    fn report_counts_and_lists_friction() {
        let data = sample();
        assert_eq!(data.total_friction(), 1);
        let md = data.to_markdown();
        assert!(md.contains("DefenderATEVET17"));
        assert!(md.contains("azork-oit-nav"));
        assert!(md.contains("unresolved-intent"));
        assert!(md.contains("verified absent"));
    }

    #[test]
    fn clean_run_reports_no_friction() {
        let mut data = sample();
        data.runs.retain(|r| r.clean());
        data.improvements.clear();
        data.issues.clear();
        let md = data.to_markdown();
        assert!(md.contains("No friction surfaced in this run."));
    }
}
